name: launchdarkly_dart_client
description: Client-side SDK code for dart.
version: 0.0.1
homepage: https://github.com/launchdarkly/flutter-client-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.2
  launchdarkly_dart_common: 0.0.1
  launchdarkly_event_source_client: 0.0.1
  crypto: ^3.0.3
  uuid: ^3.0.7

dev_dependencies:
  test: ^1.24.3
  lints: ^3.0.0
  mocktail: ^1.0.1
