version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/packages/flutter_client_sdk/example/android"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "gradle"
    directory: "/packages/flutter_client_sdk/example/android/app"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/apps/flutter_client_contract_test_service"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/apps/sse_contract_test_service"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/packages/common_client"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/packages/event_source_client"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/packages/flutter_client_sdk"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "pub"
    directory: "/packages/flutter_client_sdk/example"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
