name: launchdarkly_dart_sdks

environment:
  sdk: '>=3.4.0 <4.0.0'

packages:
  - packages/*
  - packages/flutter_client_sdk/example
  - apps/*

scripts:
  analyze:
    exec: dart analyze --fatal-infos .

  fix:
    exec: dart fix --apply .

  test:
    # Add more packages as more of them have tests.
    # Tests are ran with flutter as it supports coverage. Some packages may also include flutter
    # dependencies.
    run: MELOS_PACKAGES="launchdarkly_dart_common,launchdarkly_common_client,launchdarkly_flutter_client_sdk" melos exec -- flutter test . --coverage

  merge-trace-files:
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH --filters '\.g\.dart'"

  coverage-report:
    run: >
      melos run merge-trace-files &&
      coverde value -i coverage/filtered.lcov.info

  coverage-report-html:
    run: >
      melos run merge-trace-files &&
      coverde report -i coverage/filtered.lcov.info -o coverage/html/

  sse-contract-tests:
    run: >
      dart run apps/sse_contract_test_service/bin/sse_contract_test_service.dart &
      curl -s https://raw.githubusercontent.com/launchdarkly/sse-contract-tests/v2.0.0/downloader/run.sh | VERSION=v2 PARAMS="-url http://localhost:8080 -debug -stop-service-at-end" sh

  client-contract-tests:
    run: >
      cd apps/flutter_client_contract_test_service &&
      flutter test bin/contract_test_service.dart &
      cd apps/flutter_client_contract_test_service && curl -s https://raw.githubusercontent.com/launchdarkly/sdk-test-harness/main/downloader/run.sh | VERSION=v2 PARAMS="-url http://localhost:8080 -debug -status-timeout 100 -stop-service-at-end -skip-from testharness-suppressions.txt" sh
