name: sse_contract_test_service
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.3.0
  freezed_annotation: ^2.4.1
  openapi_base: ^1.1.0+3
  launchdarkly_flutter_client_sdk:
    path: ..

dev_dependencies:
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.21.0
  openapi_code_builder: ^1.1.4+4
  json_serializable: ^6.7.1
  build_runner: ^2.4.6