version: 2.1

jobs:
  build:
    macos:
      xcode: "13.4.1"
    resource_class: macos.x86.medium.gen2
    shell: /bin/bash --login -eo pipefail
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xms2048m -Xmx4096m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: "/tmp/Android"
      ANDROID_SDK_HOME: "/tmp/Android"
      ANDROID_SDK_ROOT: "/tmp/Android"

    steps:
      - checkout

      - run:
          name: Prepare build
          command: ./.ldrelease/prepare.sh

      - run:
          name: Run pure Dart tests
          command: flutter test

      - run:
          name: Run Android plugin native tests
          command: cd example/android && ./gradlew testDebugUnitTest

      - run:
          name: Build Android application APK
          command: cd example && flutter build apk --debug

      - run:
          name: Build iOS application
          command: cd example && flutter build ios --simulator

      - run:
          name: Build documentation
          command: dartdoc
          when: always

      - store_artifacts:
          path: doc
