name: launchdarkly_common_client
description: Client-side SDK code for dart. This is an internal package not designed for general use.
version: 1.5.0
homepage: https://github.com/launchdarkly/flutter-client-sdk
repository: https://github.com/launchdarkly/flutter-client-sdk/tree/main/packages/common_client

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  http: ^1.1.2
  launchdarkly_dart_common: 1.3.0
  launchdarkly_event_source_client: 1.0.0
  crypto: ^3.0.3
  uuid: ">= 3.0.7 <5.0.0"

dev_dependencies:
  test: ^1.24.3
  lints: ^3.0.0
  mocktail: ^1.0.1
