name: Shared Publishing Actions

description: Publish a package based on the package directory.
inputs:
  package_path:
    description: 'Path to the workspace to publish. Relative to the repository root'
    required: true

runs:
  using: composite
  steps:
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'
        channel: 'stable'

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.package_path }}
      run: flutter pub get

    - name: Publish Package
      shell: bash
      working-directory: ${{ inputs.package_path }}
      run: flutter pub publish --force