name: Shared Publishing Actions

description: Publish a package based on the package directory.
inputs:
  package_path:
    description: 'Path to the workspace to publish. Relative to the repository root'
    required: true

runs:
  using: composite
  steps:
    - name: Install Dart
      uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
      with:
        sdk: '3.7.2'

    - name: Install Flutter
      uses: subosito/flutter-action@0ca7a949e71ae44c8e688a51c5e7e93b2c87e295 # v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.package_path }}
      run: flutter pub get

    - name: Publish Package
      shell: bash
      working-directory: ${{ inputs.package_path }}
      run: flutter pub publish --force