name: flutter_sdk_contract_test_service
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.4.0

publish_to: none

dependencies:
  args: ^2.3.0
  openapi_base: ^1.1.0+3
  freezed_annotation: ^2.4.1
  # Allow setting mock implementation.
  connectivity_plus: 5.0.2
  launchdarkly_flutter_client_sdk:
    path: ../../packages/flutter_client_sdk

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.3
  openapi_code_builder: ^1.1.4+4
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
