name: launchdarkly_flutter_client_sdk
description: Official Flutter client-side SDK for LaunchDarkly. Get started using LaunchDarkly today!
version: 4.11.1
homepage: https://github.com/launchdarkly/flutter-client-sdk
repository: https://github.com/launchdarkly/flutter-client-sdk/tree/main/packages/flutter_client_sdk

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ">=4.2.0 <9.0.0"
  device_info_plus: ">=9.1.1 <12.0.0"
  launchdarkly_common_client: 1.6.1
  shared_preferences: ^2.2.2
  connectivity_plus: ">=5.0.2 <7.0.0"
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  lints: ^3.0.0
  mocktail: ^1.0.1

# The following section is specific to Flutter.
flutter:
