name: launchdarkly_flutter_client_sdk
description: Official Flutter client-side SDK for LaunchDarkly.
version: 4.0.0-alpha.0
homepage: https://github.com/launchdarkly/flutter-client-sdk/tree/main/packages/flutter_client_sdk
repository: https://github.com/launchdarkly/flutter-client-sdk


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  launchdarkly_common_client: 0.0.2
  launchdarkly_dart_common: 0.0.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  lints: ^3.0.0
  mocktail: ^1.0.1

# The following section is specific to Flutter.
flutter:
