name: launchdarkly_dart_common
description: Common dart libraries used by LaunchDarkly SDKs. This is an internal package not designed for general use.
version: 1.0.0
homepage: https://github.com/launchdarkly/flutter-client-sdk
repository: https://github.com/launchdarkly/flutter-client-sdk/tree/main/packages/common

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  # http uses http_parser, so the versions should be kept compatible.
  http_parser: ^4.0.0
  uuid: ">= 3.0.7 <5.0.0"
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.3
  mocktail: ^1.0.1
  lints: ^3.0.0
