version: 2

repo:
  public: flutter-client-sdk
  private: flutter-client-sdk-private

publications:
  - url: https://pub.dev/packages/launchdarkly_flutter_client_sdk
    description: pub

jobs:
  - circleCI:
      context: org-global
      timeoutMinutes: 20
      mac:
        xcode: "13.4.1"
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      ANDROID_HOME: "/tmp/Android"
      ANDROID_SDK_HOME: "/tmp/Android"
      ANDROID_SDK_ROOT: "/tmp/Android"

documentation:
  gitHubPages: true

sdk:
  displayName: "Flutter (client-side)"
