# This is a composite to allow sharing these steps into other workflows.
# It isn't a shared workflow, because then it isn't convenient to add
# additional workflow specific steps. This workflow is used for both CI and release process.
name: Shared CI Workflow

inputs:
  github_token:
    description: "Github token used to access contract test harness."
    required: true

description: Shared build and test for CI and release.
runs:
  using: composite
  steps:
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'
        channel: 'stable'

    - name: Install Melos
      shell: bash
      run: |
        dart pub global activate melos
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      shell: bash
      run: melos bs

    - name: Lint
      shell: bash
      run: melos run analyze

    - name: Style
      shell: bash
      # This will have a non-zero exit code if any files changed.
      run: dart format --output=none --set-exit-if-changed .

    - name: Test
      shell: bash
      run: melos run test

    - name: Contract Tests
      shell: bash
      run: |
        pushd apps/flutter_client_contract_test_service
        flutter test bin/contract_test_service.dart > test-service.log 2>&1 & disown
    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.1
      with:
        test_service_port: 8080
        token: ${{ inputs.github_token }}
        extra_params: '-status-timeout 100 --skip-from=./apps/flutter_client_contract_test_service/testharness-suppressions.txt'

    - name: SSE Contract Tests
      shell: bash
      run: |
        pushd apps/sse_contract_test_service
        dart run bin/sse_contract_test_service.dart > test-service.log 2>&1 & disown
        curl -s https://raw.githubusercontent.com/launchdarkly/sse-contract-tests/v2.0.0/downloader/run.sh | VERSION=v2 PARAMS="-url http://localhost:8080 -debug -stop-service-at-end" sh
        popd

    - name: Upload Test Service Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        path: apps/sse_contract_test_service/test-service.log

    - name: Build Docs
      shell: bash
      # Just document the end SDK package for now.
      run: melos exec --scope launchdarkly_flutter_client_sdk dart doc
