# This is a composite to allow sharing these steps into other workflows.
# It isn't a shared workflow, because then it isn't convenient to add
# additional workflow specific steps. This workflow is used for both CI and release process.
name: Shared CI Workflow

description: Shared build and test for CI and release.
runs:
  using: composite
  steps:
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'
        channel: 'stable'

    - name: Install Melos
      shell: bash
      run: |
        dart pub global activate melos
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      shell: bash
      run: melos bs

    - name: Lint
      shell: bash
      run: melos run analyze

    - name: Test
      shell: bash
      run: melos run test

    - name: Contract Tests
      shell: bash
      run: |
        cd apps/flutter_client_contract_test_service
        flutter test bin/contract_test_service.dart > test-service.log 2>&1 & disown
        curl -s https://raw.githubusercontent.com/launchdarkly/sdk-test-harness/master/downloader/run.sh | VERSION=v2 PARAMS="-url http://localhost:8080 -debug -stop-service-at-end -skip-from apps/flutter_client_contract_test_service/testharness-suppressions.txt" sh

    - name: SSE Contract Tests
      shell: bash
      run: |
        cd apps/sse_contract_test_service
        dart run bin/sse_contract_test_service.dart > test-service.log 2>&1 & disown
        curl -s https://raw.githubusercontent.com/launchdarkly/sse-contract-tests/v2.0.0/downloader/run.sh | VERSION=v2 PARAMS="-url http://localhost:8080 -debug -stop-service-at-end" sh

    - name: Upload Test Service Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        path: apps/sse_contract_test_service/test-service.log

    - name: Build Docs
      shell: bash
      # Just document the end SDK package for now.
      run: melos exec --scope launchdarkly_flutter_client_sdk dart doc
