name: launchdarkly_event_source_client
description: Server-sent events (SSE) client implementation for dart and flutter.
version: 0.0.4
homepage: https://github.com/launchdarkly/flutter-client-sdk
repository: https://github.com/launchdarkly/flutter-client-sdk/tree/main/packages/event_source_client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.3
  mocktail: ^1.0.1
  lints: ^3.0.0
