name: example_fdv2
description: "Manual testing app for the FDv2 data system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # This defaults to a published package. Using `flutter pub get` will get the
  # package from pub.dev. If you run `melos bs` in the root of the repository,
  # then it will be linked to the local version instead.
  launchdarkly_flutter_client_sdk: 4.19.0 # x-release-please-version
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
