name: Build and Test

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: shared
        name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
