name: Publish flutter client to pub.dev

on:
  push:
    tags:
      # The flutter_client_sdk was published before being a monorepo, and needs to support publishing
      # previous versions, so we omit the component and v from the tag.
      # Currently this branch should only publish 4.x releases.
      - '4.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # We override the example dependencies so the version number can be a version which has
        # not been released.
      - name: Override example dependencies
        run: |
          echo "dependency_overrides:\r\n  launchdarkly_flutter_client_sdk:\r\n    path: .." > example/pubspec_overrides.yaml
      - name: Publish Flutter Client SDK Package
        uses: ./.github/actions/publish
        with:
          package_path: packages/flutter_client_sdk
