name: Publish common to pub.dev

on:
  push:
    tags:
      - 'launchdarkly_dart_common\-v[0-9]+.[0-9]+.[0-9]+.*'

jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Common Package
        uses: ./.github/actions/publish
        with:
          package_path: packages/common
