on:
  push:
    branches:
      - rlamb/implement-release-process
name: release-please

# Unlike our other release-please workflows this one does not publish the packages directly.
# This is because the publishing configuration for pub.dev requires that the published be
# be triggered by tags being created. So this will make the changelogs and tags, and then additional
# workflows are responsible for publishing.

# At this time cross dependent packages require their version numbers to be updated manually.

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: rlamb/implement-release-process
