on:
  push:
    branches:
      - main
name: release-please

# Unlike our other release-please workflows this one does not publish the packages directly.
# This is because the publishing configuration for pub.dev requires that the published be
# be triggered by tags being created. So this will make the changelogs and tags, and then additional
# workflows are responsible for publishing.

# At this time cross dependent packages require their version numbers to be updated manually.

jobs:
  release-please:
    # Needed to get tokens during publishing.
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Normally a workflow cannot trigger another workflow. For this workflow we need to create a
      # tag that will trigger another workflow. Github determines that something is created by
      # a workflow/bot based on the token. So to allow the tag creation to trigger a workflow
      # we must use a personal access token.
      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.0.1
        name: "Get PAT"
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: "/production/common/releasing/flutter_gh_pat = GITHUB_PAT"
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ env.GITHUB_PAT }}
          default-branch: main
